hf_version: nhf_1.2.2  # options: nhf, v2.2
domain: conus  # options: conus, ak, hi, prvi
attr_dataset: hydroatlas # options: hlr, ngen, streamcat, hydroatlas
attr_list: 
overlap_threshold_max: 0.99
overlap_threshold_min: 0.2
base_dir: ~/data/region_input/{hf_version}
gpkg_dir: ~/repos/nwm-region-mgr/data/inputs/region/hydrofabric/gpkg_vpu
cwt_file: '{base_dir}/cwt_ngen_{attr_dataset}/cwt_ngen_{attr_dataset}_{domain}.parquet'
attr_file: '{base_dir}/attr_datasets/{attr_dataset}/attr_{attr_dataset}_{domain}.parquet'
process_cwt: true
analyze_cwt: true
process_attr: true

hlr:
  hf_file: ~/data/hlrshape/hlrus.shp
  layer: hlrus
  id_col: VALUE
  attr_list_file: attr_config_template/nhf/attr_selection_hlr.csv

ngen:
  layer: divides
  id_col: div_id   #div_id for nhf, divide_id for v2.2
  vpu_col: vpuid #vpuid for nhf, vpu_id for v2.2
  attr_list_file: attr_config_template/nhf/attr_selection_ngen.csv

streamcat:
  hf_file: '~/data/NHDPlusV21/NHD_by_vpu/NHDPlus{vpu}/NHDPlusCatchment/Catchment.shp'
  layer: Catchment
  id_col: FEATUREID
  vpu_col: vpuid
  attr_data_dir: ~/data/streamcat
  attr_list_file: attr_config_template/nhf/attr_selection_streamcat.csv

hydroatlas:
  hf_file: '~/data/HydroATLAS/BasinATLAS_v10_shp/BasinATLAS_v10_lev12.shp'
  layer: BasinATLAS_v10_lev12
  id_col: PFAF_ID
  attr_list_file: attr_config_template/nhf/attr_selection_hydroatlas.csv


