# Configuration for NGEN simulation. 
general:
  # ------ fields overridding config_general.yaml
  # run_name: test  # Name of the run, used to create output folders and files
  # domain: conus  # Define NWM domain. Supported options: conus, ak, hi, prvi
  # vpu_list: ['03S'] # List of VPUs to process.
  # n_procs: 1  # Number of processors to use 
  # base_dir: '${WORK_DIR}' # Path to the base directory, with WORK_DIR set via docker run 
  # static_data_dir: '${REPOS_COMMON_ROOT__HOST}/nwm-region-mgr/data/inputs'  # Path to the static data directory   
  # ngen_hydrofabric_file: '{static_data_dir}/hydrofabric/gpkg_vpu/vpu_{vpu_list}.gpkg'  

  logging: # define logging configurations
    level: info  # logging level, options: debug, info, warning, error, critical
    log_to_file: True  # whether to log to a file
    file: '{base_dir}/outputs/ngen/{run_name}/ngen_{domain}.log'

  # ----- fields unique to NGEN simulation (i.e., not in config_general.yaml) ----
  start_time: '2012-10-01T00:00:00'
  end_time: '2012-10-01T10:00:00'
  algorithm_list: ['kmeans']  # list of algorithms to use for parameter regionalization
  par_file: '{base_dir}/outputs/region/{run_name}/params/formulation_params_{algorithm_list}_{domain}_vpu{vpu_list}.csv'
  pair_file: '{base_dir}/outputs/region/{run_name}/pairs/pairs_{algorithm_list}_{domain}_vpu{vpu_list}_mswm.csv'
  config_template: '{static_data_dir}/ngen/mswm.config.template.docker'

output:
  ngen:
    save: true
    path: '{base_dir}/outputs/ngen/' # root directory for NGEN simulation inputs/outputs (with sub-folders created by MSWM as needed)
  config_final: # Final configuration file after processing and validation
    save: True
    path: '{base_dir}/outputs/ngen/{run_name}'
    stem: 'config_ngen_final_{domain}_vpu{vpu_list}'
    format: yaml